var cardInfo = {
  "New Earth": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Earth", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume any good for 1 VP and 1 card", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "Rare Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Survey SETI": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Survey SETI", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "See +2", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Base": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Base", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "6", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Bazaar": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Galactic Bazaar", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Discard up to 2 cards for 1 VP each", 
    "Goods": "Novelty", 
    "Trade": "Trade Novelty +1 card", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Export Duties": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Export Duties", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "Trade any +1 card", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "New Military Tactics": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Military Tactics", 
    "Phase III": "Discard from tableau for Military +3 this phase", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Alien Tourist Attraction": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Tourist Attraction", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Consume any good for 1 VP and 2 cards", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "See +1", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Pan-Galactic Security Council": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Pan-Galactic Security Council", 
    "Phase III": "May spend 1 prestige to automatically defeat a take over attempt against any player's tableau", 
    "Production": "", 
    "Consume": "May discard 2 cards to gain 1 prestige", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "New Survivalists": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Survivalists", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume Novelty good for 1 card", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Pan Galactic League": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Pan Galactic League", 
    "Phase III": "Military -1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Draw 1 card for each Genes card in tableau", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-1", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Black Hole Miners": {
    "Other": "Round end: discard down to 12 cards instead of 10", 
    "Set": "Brink of War", 
    "Name": "Black Hole Miners", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "Draw 3 cards", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Star Nomad Lair": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Star Nomad Lair", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "Trade Novelty good on this world for +1 card", 
    "VP": "1", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Last Uplift Gnarssh": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Last Uplift Gnarssh", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Data Repository": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Alien Data Repository", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "6", 
    "Explore": "Explore into Hand", 
    "Cost": "7", 
    "Phase V": "Alien Good", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Plague World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Plague World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume Genes good for 1 VP and 1 card", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Genes Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Monolith": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Alien Monolith", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "8", 
    "Explore": "", 
    "Cost": "8", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Golden Age of Terraforming": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Golden Age of Terraforming", 
    "Phase III": "may discard a genes good for -3 cost to place a nonmilitary world; put a good on a production world when placing it", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Terraforming", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": "may discard a rare good for -2 to place a development"
  }, 
  "Rebel Sneak Attack": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Rebel Sneak Attack", 
    "Phase III": "May discard after placing a world to place a military world; may discard to take over a military world from an Imperium tableau adding 2 military for each rebel military world in your tableau", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "Explore into Hand", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Galactic Advertisers": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Galactic Advertisers", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Draw 1 card", 
    "Goods": "", 
    "Trade": "Trade any +1 card", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Freedom Fighters": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Rebel Freedom Fighters", 
    "Phase III": "Military +1; Military -2 if you have an Imperium card; Gain 1 prestige after placing a rebel military world", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "See +1", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": "Gain 1 prestige after placing a rebel development"
  }, 
  "Diversified Economy": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Diversified Economy", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume three different kinds of goods to gain 3 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "Draw one card for each kind of good you produced ", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Imperium Lords": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Imperium Lords", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Draw 1 card for each military world in tableau", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Insect Uplift Race": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Insect Uplift Race", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Investment Credits": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Investment Credits", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "Development cost -1"
  }, 
  "Hive World": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Hive World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Genes Good", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Tech Institute": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Alien Tech Institute", 
    "Phase III": "Alien cost -2/military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Smuggling World": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Smuggling World", 
    "Phase III": "Place Novelty cost -1/military +1", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "Explore into Hand", 
    "Cost": "1", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Blaster Gem Consortium": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Imperium Blaster Gem Consortium", 
    "Phase III": "Military +1", 
    "Production": "Production", 
    "Consume": "Consume Rare for 1 VP and 2 cards", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Rare Good", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Blaster Gem Mines": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Blaster Gem Mines", 
    "Phase III": "Military +1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Bio-hazard Mining World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Bio-hazard Mining World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "Trade Genes +2 card", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Rare Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Comet Zone": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Comet Zone", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Rare Good; When produce Rare good on this world, draw 1 card", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Deficit Spending": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Deficit Spending", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Discard up to 2 cards for 1 VP each", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Distant World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Distant World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "Sell novelty +3 cards", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "Genes Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Spice World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Spice World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "Trade Novelty +2 card", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Devolved Uplift Race": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Devolved Uplift Race", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Novelty Good", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "New Sparta": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Sparta", 
    "Phase III": "Military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": "2", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Engineers": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Engineers", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "Trade any +1 card", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Produce on any other Windfall", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Blaster Runners": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Blaster Runners", 
    "Phase III": "Military +1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "Explore into Hand", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Renaissance": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Renaissance", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "See +2, Keep +1", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Pre-Sentient Race": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Pre-Sentient Race", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Hidden Fortress": {
    "Other": "Tableau to end game is 14 cards", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Hidden Fortress", 
    "Phase III": "Military +1 for each military world in your tableau", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Radioactive World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Radioactive World", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Terraforming Robots": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Terraforming Robots", 
    "Phase III": "After settle draw 1 card", 
    "Production": "", 
    "Consume": "Consume Rare good for 1 VP and 1 card", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "Terraforming", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Uplift Mercenary Force": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Uplift Mercenary Force", 
    "Phase III": "Military +1 for each Chromosome world; may discard 1 card for +1 military", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "See +1", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Armaments World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Imperium Armaments World", 
    "Phase III": "Military +1", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "Rare Good", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Terraformed World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Terraformed World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "5", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Capital": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Imperium Capital", 
    "Phase III": "Gain 1 prestige after placing a Rebel military world", 
    "Production": "", 
    "Consume": "Consume any 2 goods for 2 prestige", 
    "Goods": "", 
    "Trade": "", 
    "VP": "6", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Mining Robots": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Mining Robots", 
    "Phase III": "Place Rare cost -1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Produce on Rare windfall world", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Deserted Alien World": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Deserted Alien World", 
    "Phase III": "Alien cost -2/military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Bankers": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Galactic Bankers", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Discard up to 2 cards for 1 VP each", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "Draw 1 card"
  }, 
  "Alien Oort Cloud Refinery": {
    "Other": "Any phase, game end: choose this world's kind", 
    "Set": "Brink of War", 
    "Name": "Alien Oort Cloud Refinery", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Any", 
    "Trade": "You may not sell a good from this world", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "0", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Mining Mole Uplift Race": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Mining Mole Uplift Race", 
    "Phase III": "Place Rare cost -1", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "3", 
    "Phase V": "Rare good", 
    "Keywords": "UpliftX", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Federation Capital": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Federation Capital", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 prestige", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": "Gain 1 prestige after placing a 6-cost development"
  }, 
  "Public Works": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Public Works", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "After development draw 1 card"
  }, 
  "Dying Colony": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Dying Colony", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": 0, 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Toy Shop": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Alien Toy Shop", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Consume Alien good from this world for 2 VP", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Consumer Markets": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Consumer Markets", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume up to 3 Novelty goods for 1 point", 
    "Goods": "", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "Draw 1 card for each Novelty good produced", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Uplift Code": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Uplift Code", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Draw 2 cards for each gene symbol uplift world in your tableau", 
    "Keywords": "Uplift", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Avian Uplift Race": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Avian Uplift Race", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Deserted Alien Colony": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Deserted Alien Colony", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Power Brokers": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Galactic Power Brokers", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "May spend 1 prestige to draw 3 cards", 
    "Goods": "", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": "draw 2 cards at the start of this phase, then discard 1 card from your hand"
  }, 
  "Pan-Galactic Affluence": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Pan-Galactic Affluence", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any 2 goods for 1 prestige and 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Draw 1 card if you produced the most goods this phase", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": "Gain 1 prestige after placing a development"
  }, 
  "Interstellar Prospectors": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Interstellar Prospectors", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "3", 
    "Phase V": "Rare Good; Produce on other Rare Windfall", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Retrofit & Salvage, Inc": {
    "Other": "Round end: take any cards discarded by other players into your hand", 
    "Set": "Brink of War", 
    "Name": "Retrofit & Salvage, Inc", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": "Development cost -1"
  }, 
  "Ravaged Uplift World": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Ravaged Uplift World", 
    "Phase III": "May place a chromosome military world as a non-military world", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "-1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Gain 1 prestige if you have the most chromosome worlds in tableau", 
    "Keywords": "UpliftX", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Clandestine Uplift Lab": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Clandestine Uplift Lab", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP and 1 card", 
    "Goods": "", 
    "Trade": "Trade Genes +1 card per genetic symbol", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Deserted Alien Outpost": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Deserted Alien Outpost", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Departure Point": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Departure Point", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "9", 
    "Explore": "At start of phase, may discard 1 card to gain 1 prestige", 
    "Cost": "9", 
    "Phase V": "Alien Good", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Gene Designers": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Gene Designers", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume Genes for 1 VP and 1 card three times", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Genes Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Information Hub": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Information Hub", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "Explore into Hand", 
    "Cost": "3", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": "draw 1 card at the start of this phase, then discard 1 card from hand"
  }, 
  "Space Port": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Space Port", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "Trade Rare +2 card", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Mercenary Fleet": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Mercenary Fleet", 
    "Phase III": "Military +2; Discard up to 2 cards military +1 each this phase", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "2", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Sympathizers": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Rebel Sympathizers", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Draw 1 card when produce Novelty good on this world", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Burial Site": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Burial Site", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "Trade Novelty +1 card", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Earths Lost Colony": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Earths Lost Colony", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Robot Sentry": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Alien Robot Sentry", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Imperium": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Imperium", 
    "Phase III": "Military +4 against rebel worlds", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Imperium Invasion Fleet": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Imperium Invasion Fleet", 
    "Phase III": "Military +3; Military +1 vs. Rebel; may discard to place a nonmilitary world as a military world and gain 2 prestige", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": "3", 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Fuel Cache": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Fuel Cache", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Fuel Depot": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Imperium Fuel Depot", 
    "Phase III": "draw 2 cards after you place a world, then discard 1 card from hand", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Rare good", 
    "Keywords": "Imperium", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Robotic Factory": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Alien Robotic Factory", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "5", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Alien Good", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Warrior Race": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Warrior Race", 
    "Phase III": "Military +1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Primitive Rebel World": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Primitive Rebel World", 
    "Phase III": "Discard card for military +1 this phase", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Former Penal Colony": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Former Penal Colony", 
    "Phase III": "Military +1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Salon": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Galactic Salon", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Gain 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Expanding Colony": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Expanding Colony", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Produce on Novelty windfall world", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Markets": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Galactic Markets", 
    "Phase III": "Draw 1 card after you place a world", 
    "Production": "", 
    "Consume": "Consume up to 3 of any good for 1 VP each", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "Draw 1 card", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Terraforming Engineers": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Terraforming Engineers", 
    "Phase III": "Any cost -1; may replace one non-military world with another of cost 0-3 higher of the same kind to gain 1 prestige", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "Terraforming", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Council": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Rebel Council", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "8", 
    "Explore": "", 
    "Cost": "8", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": "Gain 1 prestige after placing a rebel development"
  }, 
  "Terraforming Guild": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Terraforming Guild", 
    "Phase III": "After settle draw 1 card", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Produce on any windfall world", 
    "Keywords": "Terraforming", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Psi-Crystal World": {
    "Other": "Round start: select your action after all other players turn up their action cards", 
    "Set": "Brink of War", 
    "Name": "Psi-Crystal World", 
    "Phase III": "Military -1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "See +1", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-1", 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Reptilian Uplift Race": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Reptilian Uplift Race", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "New Vinland": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Vinland", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume any good for 2 cards", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Aquatic Uplift Race": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Aquatic Uplift Race", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Uplift Center": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Alien Uplift Center", 
    "Phase III": "Place Alien cost -2/military +2", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "See +1", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "Alien Uplift", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Robot Scout Ship": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Alien Robot Scout Ship", 
    "Phase III": "Military +1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Pilgrimage World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Pilgrimage World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume all remaining goods for 1 VP each minus 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "0", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Troops": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Imperium Troops", 
    "Phase III": "Military +1; Military +1 vs. Rebel", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Galactic Scavengers": {
    "Other": "put 1 card from your hand under this world before selecting your first action", 
    "Set": "Brink of War", 
    "Name": "Galactic Scavengers", 
    "Phase III": "Save 1 card from your payment under this world", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Draw all cards under this world", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": "Save 1 card from your payment under this world"
  }, 
  "Volcanic World": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Volcanic World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Rare Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Studios": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Galactic Studios", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume any good for 1 VP and 1 card", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "Novelty Good; When produce Novelty good on this world, draw 1 card", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Underground": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Underground", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Draw 1 card", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Drop Ships": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Drop Ships", 
    "Phase III": "Military +3", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "3", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Outlaw World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Outlaw World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP and 1 card", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Malevolent Lifeforms": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Malevolent Lifeforms", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "4", 
    "Phase V": "Genes Good", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Pirate World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Pirate World", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "Trade Novelty good on this world for +3 cards", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Pact": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Rebel Pact", 
    "Phase III": "Cost -2 when using a Military into Non-Military Power; +2 defense against attack for each rebel world in tableau, +1 for each other military world", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "Explore into Hand", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Pan-Galactic Hologrid": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Pan-Galactic Hologrid", 
    "Phase III": "Draw 1 card after you place a world", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "Trade Novelty at +2", 
    "VP": 0, 
    "Explore": "At start of phase, may discard 1 card to gain 1 prestige", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Research Labs": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Research Labs", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume Genes for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "Keep +1", 
    "Cost": "4", 
    "Phase V": "Draw one cards for each Alien good produced", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Alien Booby Trap": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Booby Trap", 
    "Phase III": "May spend 1 prestige for +2 military this phase", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "May discard 1 card to produce on an alien windfall", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Stronghold": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Rebel Stronghold", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "9", 
    "Explore": "", 
    "Cost": "9", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Lost Alien Warship": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Lost Alien Warship", 
    "Phase III": "Military +2", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": "2", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Mining League": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Mining League", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume 2 Rare goods for 3 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Produce on Rare windfall world", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Improved Logistics": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Improved Logistics", 
    "Phase III": "May placed a second world after the first world is placed", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Alien Rosetta Stone World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Alien Rosetta Stone World", 
    "Phase III": "Alien cost -2/military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Expedition Force": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Expedition Force", 
    "Phase III": "Military +1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Genetics Lab": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Genetics Lab", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "Trade Genes +1 card", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Produce on Genes windfall world", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Lifeforms, Inc": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Lifeforms, Inc", 
    "Phase III": "may discard a genes good for -3 cost to place a nonmilitary world", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Genes Good; may discard 1 card to produce on one Genes windfall", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Uplift Revolt World": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Uplift Revolt World", 
    "Phase III": "Military +1 for each Chromosome world", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "UpliftX", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Miners": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Miners", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Rare Good", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Alliance": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Rebel Alliance", 
    "Phase III": "May place a rebel military world as a non-military world at cost -2; May take over military worlds in Imperium tableau adding military +2 for each rebel world in your tableau", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Deserted Alien Library": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Deserted Alien Library", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "5", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Developers": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Galactic Developers", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume good for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": "Draw 1 card"
  }, 
  "Abandoned Alien Uplift Camp": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Abandoned Alien Uplift Camp", 
    "Phase III": "Place Genes cost -2/military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Alien Uplift", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Universal Exports": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Universal Exports", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "Trade +1 card", 
    "VP": "2", 
    "Explore": "Explore into Hand", 
    "Cost": "3", 
    "Phase V": "Novelty Good; May discard 1 card to produce on a windfall", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Guardian": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Guardian", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "May discard 2 cards to gain 1 prestige", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "9", 
    "Explore": "", 
    "Cost": "9", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Seat": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Imperium Seat", 
    "Phase III": "Military +1 to place rebel military world; May take over rebel military worlds", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Galactic Trendsetters": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Trendsetters", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 2 VPs", 
    "Goods": "", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Outpost": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Outpost", 
    "Phase III": "Military +1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "5", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Universal Peace Institute": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Universal Peace Institute", 
    "Phase III": "Military -2; Place cost -2", 
    "Production": "", 
    "Consume": "Consume any 2 goods for 1 prestige, 1 VP, 1 card", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-2", 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Smuggling Lair": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Smuggling Lair", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Consume any good for 2 cards", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Space Marines": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Space Marines", 
    "Phase III": "Military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "2", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Ancient Race": {
    "Other": "Discard down to 3 cards before selecting a first round action if this is your start world", 
    "Set": "Gathering Storm", 
    "Name": "Ancient Race", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Damaged Alien Factory": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Damaged Alien Factory", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Discard 1 card to produce Alien Good", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Contact Specialist": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Contact Specialist", 
    "Phase III": "Military -1; Settle Non-Alien Military world as non-Military world at cost -1 ", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-1", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Lost Alien Battle Fleet": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Lost Alien Battle Fleet", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Alien", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Alien Good", 
    "Keywords": "Alien", 
    "Military": "X", 
    "Strength": "3", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Secluded World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Secluded World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume any good for 1 card", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alpha Centauri": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Alpha Centauri", 
    "Phase III": "Rare cost -1/military +1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Merchant Guild": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Merchant Guild", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Draw 2 cards", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Black Market Trading World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Black Market Trading World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good to draw card's equal to goods trade value", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Refugee World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Refugee World", 
    "Phase III": "Military -1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "0", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Uplift Gene Breeders": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Uplift Gene Breeders", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Genes good; Gain 1 prestige when producing a genes good on this world", 
    "Keywords": "Uplift", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Pan-Galactic Research": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Pan-Galactic Research", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "See +2, Keep +1", 
    "Cost": "6", 
    "Phase V": "Draw 2 cards", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "Development cost -1"
  }, 
  "Mining Conglomerate": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Mining Conglomerate", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume up to 2 Rare goods fro 1 vp each", 
    "Goods": "", 
    "Trade": "Trade Rare +2 card", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Draw 2 cards if you produce the most Rare goods", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Free Trade Association": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Free Trade Association", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume Novelty good for 1 VP and 1 card up to three times", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Produce on Novelty windfall world", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Runaway Robots": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Runaway Robots", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Draw 1 card when produce Rare good on this world", 
    "Keywords": "", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Old Earth": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Old Earth", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume up to 2 goods for 1 VP each", 
    "Goods": "", 
    "Trade": "Trade any +1 card", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Empath World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Empath World", 
    "Phase III": "Military -1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Artist Colony": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Artist Colony", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Epsilon Eridani": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Epsilon Eridani", 
    "Phase III": "Military +1", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP and 1 card", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Interstellar Casus Belli": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Interstellar Casus Belli", 
    "Phase III": "May spend 1 prestige to take over a military world from any tableau, if successful, gain 2 prestige", 
    "Production": "", 
    "Consume": "May spend 1 prestige to gain 3 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Gambling World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Gambling World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP; name 1-7 and flip a card, keep if cost or defense matches", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Cloaking Technology": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Imperium Cloaking Technology", 
    "Phase III": "Discard to take over a military world at -2 cost; Discard to take over a military world from a tableau that has at least +1 military", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Merchant World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Merchant World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Discard up to 2 cards for 1 VP each", 
    "Goods": "", 
    "Trade": "Trade any +2 cards", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Destroyed World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Destroyed World", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Pan-Galactic Mediator": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Pan-Galactic Mediator", 
    "Phase III": "Military -1; Gain 1 prestige when using a military to non-military power", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "-1", 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Separatist Colony": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Separatist Colony", 
    "Phase III": "Military +1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "See +2", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Lost Species Ark World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Lost Species Ark World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "3", 
    "Explore": "", 
    "Cost": "5", 
    "Phase V": "Genes Good; When produce on this world draw 2 cards", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Genome Project": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Galactic Genome Project", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume 2 Genes good for 3 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Gem World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Gem World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Novelty Good; When produce Novelty good on this world, draw 1 card", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "R and D Crash Program": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "R and D Crash Program", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Discard card to draw a new card", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "Discard for -3 development cost"
  }, 
  "Trading Outpost": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Trading Outpost", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "Trade any +2 cards", 
    "VP": "1", 
    "Explore": "Explore into Hand", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Mining World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Mining World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Rare Good; When produce Rare good on this world, draw 1 card", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Convict Mines": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Rebel Convict Mines", 
    "Phase III": "Discard card for military +1 this phase", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Trade League": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Trade League", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good to draw card's equal to goods trade value + trade bonuses", 
    "Goods": "", 
    "Trade": "Trade any +1 card", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Prosperous World": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Prosperous World", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Novelty Good", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Space Mercenaries": {
    "Other": "", 
    "Set": "Gathering Storm", 
    "Name": "Space Mercenaries", 
    "Phase III": "Military +1; Discard card for Military +1 two times", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "0", 
    "Explore": "", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Imperium Warlord": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Imperium Warlord", 
    "Phase III": "Military +1; Military vs. Rebel +1", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "See +1", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Universal Symbionts": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Universal Symbionts", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Consume Genes for 1 VP and 1 card three times", 
    "Goods": "Genes", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "Produce on other Genes Windfall", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "New Galactic Order": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Galactic Order", 
    "Phase III": "Military +2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": "2", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Doomed World": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Doomed World", 
    "Phase III": "Discard to settle any non-Alien non-military world at  cost", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "-1", 
    "Explore": "See +1", 
    "Cost": "1", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Replicant Robots": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Replicant Robots", 
    "Phase III": "Any cost -2", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Alien Cornucopia": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Cornucopia", 
    "Phase III": "Gain 1 prestige after placing a production world", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "Draw 1 card", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Fuel Refinery": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Rebel Fuel Refinery", 
    "Phase III": "May discard a rare good for +2 military this phase", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "1", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Prospecting Guild": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Prospecting Guild", 
    "Phase III": "", 
    "Production": "Production", 
    "Consume": "Consume Rare for 1 VP and 1 card", 
    "Goods": "", 
    "Trade": "Trade any +1 card", 
    "VP": 0, 
    "Explore": "Explore into Hand", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Galactic Exchange": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Galactic Exchange", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Gain 1 VP and 1 card for each different good type consumed", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Tourist World": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Tourist World", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any 2 goods for 3 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Homeworld": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Rebel Homeworld", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "7", 
    "Explore": "", 
    "Cost": "7", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "New Economy": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "New Economy", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Draw 1 card", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Colony Ship": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Colony Ship", 
    "Phase III": "Discard to settle any non-Alien non-military world at  cost", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Galactic Resort": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Resort", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "Consume any good for 1 VP and 1 card", 
    "Goods": "Novelty", 
    "Trade": "", 
    "VP": "2", 
    "Explore": "", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Interstellar Bank": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Interstellar Bank", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "Draw 1 card"
  }, 
  "Rebel Cantina": {
    "Other": null, 
    "Set": "Rebel vs. Imperium", 
    "Name": "Rebel Cantina", 
    "Phase III": "May place any non-Alien military world as a non-military world at full price (before discounts)", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "Draw 1 card for each rebel world in your tableau", 
    "Keywords": "Rebel", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Asteroid Belt": {
    "Other": "", 
    "Set": "Race For the Galaxy", 
    "Name": "Asteroid Belt", 
    "Phase III": "", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Rebel Colony": {
    "Other": null, 
    "Set": "Gathering Storm", 
    "Name": "Rebel Colony", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "Consume any good for 1 VP", 
    "Goods": "", 
    "Trade": "", 
    "VP": "4", 
    "Explore": "", 
    "Cost": "4", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "X", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Galactic Federation": {
    "Other": null, 
    "Set": "Race For the Galaxy", 
    "Name": "Galactic Federation", 
    "Phase III": "", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": 0, 
    "Explore": "", 
    "Cost": "6", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": "Development cost -2"
  }, 
  "Gem Smugglers": {
    "Other": "", 
    "Set": "Rebel vs. Imperium", 
    "Name": "Gem Smugglers", 
    "Phase III": "Place Rare cost -1/military +1", 
    "Production": "Windfall", 
    "Consume": "", 
    "Goods": "Rare", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "Explore into Hand", 
    "Cost": "3", 
    "Phase V": "", 
    "Keywords": "", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Alien Research Team": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Alien Research Team", 
    "Phase III": "Alien cost -1; may place alien military as non-military", 
    "Production": "", 
    "Consume": "Consume an alien good for 1 prestige", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "See +2", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "Alien", 
    "Military": "", 
    "Strength": 0, 
    "Prestige": "", 
    "Type": "World", 
    "Phase II": ""
  }, 
  "Imperium Planet Buster": {
    "Other": "", 
    "Set": "Brink of War", 
    "Name": "Imperium Planet Buster", 
    "Phase III": "Military +3; May take over and destroy a military world from a tableau with at least +1 military; if successful, gain 2 prestige", 
    "Production": "", 
    "Consume": "", 
    "Goods": "", 
    "Trade": "", 
    "VP": "9", 
    "Explore": "", 
    "Cost": "9", 
    "Phase V": "", 
    "Keywords": "Imperium", 
    "Military": "", 
    "Strength": "3", 
    "Prestige": "1", 
    "Type": "Development", 
    "Phase II": ""
  }, 
  "Rebel Troops": {
    "Other": null, 
    "Set": "Brink of War", 
    "Name": "Rebel Troops", 
    "Phase III": "Military +1; May discard 1 card for +1 military this phase", 
    "Production": "", 
    "Consume": "Consume any good for 2 cards", 
    "Goods": "", 
    "Trade": "", 
    "VP": "1", 
    "Explore": "", 
    "Cost": "2", 
    "Phase V": "", 
    "Keywords": "Rebel", 
    "Military": "", 
    "Strength": "1", 
    "Prestige": "", 
    "Type": "Development", 
    "Phase II": ""
  }
};